spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        group: mengck
        metadata:
          env: env1
          group: mengck
          region: dev
          version: 1.0
          zone: zone1
        namespace: mengck
        username: nacos
        password: nacos
        register-enabled: true
        server-addr: 172.28.100.238:8848
        service: crawl-gateway
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

gateway:
  routes:
    config:
      data-id: gateway-routes  #动态路由
      group: mengck
      namespace: mengck

server:
  port: 9090